version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8084:80
#    prod ports
#      - 80:80
#      - 443:443
    volumes:
      - ./Nginx/core:/etc/nginx/conf.d
      - ./Nginx/Logs:/var/log/nginx/
      - ./:/var/www/laravel-docker
    links:
      - fpm
  fpm:
    build: ./PHP
    volumes:
      - ./:/var/www/laravel-docker
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 33064:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=parser
